blog/urls.py
from django.urls import path

from blog.views import like, post_delete, post_list, post_create, post_detail, post_update

app_name = 'blog'
urlpatterns = [
    path('', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('<str:slug>/', post_detail, name='detail'),
    path('<str:slug>/update/', post_update, name='update'),
    path('<str:slug>/delete/', post_delete, name='delete'),
    path('<str:slug>/like/', like, name='like'),
]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

urlpatterns = [
    # path("", ),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

def user_directory_path(instance, filename):
    return f'blog/{instance.author.id}/{filename}'
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural="Categories"

class Post(models.Model):
    STATUS = [
        ('draft', 'Draft'),
        ('published', 'Published'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(
        upload_to=user_directory_path, default="django.jpg")
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    published_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS, default='draft')
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural="Post"
    
    def comment_count(self):
        return self.comment_set.all().count()
    
    def view_count(self):
        return self.postview_set.all().count()
    
    def like_count(self):
        return self.like_set.all().count()
    
    def comments(self):
        return self.comment_set.all()
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
def user_profile_path(instance, filename):
    return f"user/{instance.user.id}/{filename}"


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to=user_profile_path, default="Avatar.png")
    bio = models.TextField(blank=True)

blog/forms.py
from django import forms
from .models import Category, Post, Comment


class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.STATUS)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Select Category')
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'category',
            'status'
        ]
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .forms import CommentForm, PostForm
from blog.models import Like, Post

# Create your views here.


def post_list(request):
    qs = Post.objects.filter(status='published')
    context = {
        'object_list': qs
    }
    return render(request, 'blog/post_list.html', context)


def post_create(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:list')
    context = {
        'form': form
    }
    return render(request, 'blog/post_create.html', context)


def post_detail(request, slug):
    # obj = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST or None)
    obj = Post.objects.get(slug=slug)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = obj
        comment.save()
        return redirect('blog:detail', slug=slug)
    context = {
        "object": obj,
        "form": form
    }
    return render(request, "blog/post_detail.html", context)


def post_update(request, slug):
    obj = Post.objects.get(slug=slug)
    if request.user.id != obj.author.id:
        # return HttpResponse("You are not authorized!!")
        return redirect("blog:list")
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect("blog:list")
    context = {
        "object": obj,
        "form": form
    }
    return render(request, "blog/post_update.html", context)


def post_delete(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    if request.user.id != obj.author.id:
        # return HttpResponse("You are not authorized!!")
        return redirect("blog:list")
    if request.method == 'POST':
        obj.delete()
        return redirect('blog:list')
    context = {
        'object': obj
    }
    return render(request, "blog/post_delete.html", context)


def like(request, slug):
    if request.method == 'POST':
        obj = get_object_or_404(Post, slug=slug)
        like_qs = Like.objects.filter(user=request.user, post=obj)
        if like_qs.exists():
            like_qs[0].delete()
        else:
            Like.objects.create(user=request.user, post=obj)
        return redirect('blog:detail', slug=slug)

users/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/post_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
<input type="submit" value="Create">
</form>

{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block content %}

<h4>Are you sure delete {{object}} </h4>
<form action=""method='post'>
    {% csrf_token %}
    <a href="{% url 'blog:list' %}">Cancel</a>
    <input type="submit" value="Yes I want to Delete">
</form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>{{object.title}}</h1>
    <img src="{{object.image.url}} " alt="{{object.title}}">
    <p>{{object.content}}</p>
    <div class="contianer">
        <form action="" method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Comment">
        </form>
        
        {% for comment in object.comments %}
        <div class="container border-bottom border-2 my-3">
            <h5>Comment by {{comment.user}} at {{comment.time_stamp|timesince}} ago</h5>
            <p>{{comment.content}}</p>
        </div>
        {% endfor %}
        <form action="{% url 'blog:like' object.slug %}" method='POST'>
            {% csrf_token %}
            <input type="hidden" name="post">
            <input type="hidden" name="user">
            <button type='submit'>Like</button> {{object.like_count}}
        </form>
        <div class="container m-3">
            {% if user.id == object.author.id %}
            <a href="{% url 'blog:update' object.slug %}" class="btn btn-warning mx-4">Update</a>
            <a href="{% url 'blog:delete' object.slug %}" class="btn btn-danger">Delete</a>
            {% endif %}
        </div>
            

    </div>
</div>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %} 
{% block content %} 
<div class="row mt-5">
    {% for post in object_list %}
    <div class="col-4">
        <div class="card shadow p-3 mb-5 bg-info rounded" style="width: 18rem; height: 25rem;">
            <img src="{{post.image.url}}" class="card-img-top" alt="{{post.title}}">
            <div class="card-body">
            <h5 class="card-title"><a href="{% url 'blog:detail' post.slug %} ">{{post.title}}</a></h5>
            <p class="card-text">{{post.content|truncatechars:50}}</p>
            <div>
                <i class="fa-solid fa-eye mx-2"></i><span>{{post.view_count}}</span>
                <i class="fa-regular fa-heart mx-2"></i><span> {{post.like_count}}</span>
                <i class="fa-regular fa-message mx-2"></i><span>{{post.comment_count}}</span>
            </div>
            <div class="card-text">
                <small>Posted {{post.published_date|timesince}} ago</small>
            </div>
        </div>
       
    </div>
</div>
    {% endfor %} 
</div>
{% endblock content %}

blog/templates/blog/post_update.html
{% extends 'base.html' %}
{% block content %}
<h2>Update {{object.title}}</h2>
<form action="" method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
<input type="submit" value="Update">
</form>
{% comment %} <h1>{{object.title}}</h1>
<img src="{{object.image.url}} " alt="">
<p>{{object.content}}</p> {% endcomment %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
    crossorigin="anonymous"
    />
    <title>Blog App Local</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %} 
        {% endblock content %}
    </div>
        <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
    <nav class="navbar navbar-expand-md navbar-dark bg-success text-uppercase">
    <div class="container-fluid">
      <a class="navbar-brand text-white mx-3" href="{% url 'blog:list' %}">Blog App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <ul class="navbar-nav ms-auto mb-2 me-3 mb-lg-0">
          <li class="d-none d-md-block nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:list' %}">Home</a>
          </li>
          <li class="d-none d-md-block nav-item">
            <a class="nav-link" href="">About</a>
          </li>
        </ul>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 me-3 mb-lg-0 text-center">
        {% if user.is_authenticated %}
            <li class="nav-item mx-4">
              <span class='nav-link'>{{user.username | title}}</span>
            </li>
            <li class="nav-item">
              <a class="d-block d-md-none nav-link active" aria-current="page" href="{% url 'blog:list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="d-block d-md-none nav-link" href="">About</a>
            </li>
            <li class="nav-item">
                {% comment %}  {% endcomment %}
                <a class="nav-link active" aria-current="page" href="">Logout</a>
            </li>
            <li class="nav-item">
                {% comment %} {% url 'profile' user.id %} {% endcomment %}
                <a class="nav-link" href="">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:create' %}">New Post</a>
            </li>
            
        {% else %}
            <li class="nav-item">
              <a class="d-block d-md-none nav-link active" aria-current="page" href="{% url 'blog:list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="d-block d-md-none nav-link" href="">About</a>
            </li>
            <li class="nav-item">
                {% comment %} {% url 'login' %} {% endcomment %}
                <a class="nav-link active" aria-current="page" href="">Login</a>
            </li>
            <li class="nav-item">
                {% comment %} {% url 'register' %} {% endcomment %}
                <a class="nav-link" href="">Register</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>